disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - implicit_return # Re-enable when we drop support for Swift 4.2
  - large_tuple
  - line_length
  - nesting
  - type_body_length

statement_position:
  statement_mode: uncuddled_else

opt_in_rules:
  - anyobject_protocol
  - identical_operands
  - implicit_return
  - last_where
  - legacy_random
  - operator_usage_whitespace
  - redundant_objc_attribute
  - sorted_imports
  - static_operator
  - toggle_bool
  - unused_control_flow_label
  - vertical_whitespace

trailing_comma:
  mandatory_comma: true
