//
//  BONSpecial.m
//  Pods
//
//  Created by Zev Eisenberg on 7/16/15.
//

// This file is auto-generated by scripts/BONSpecialGenerator.swift. Please do not edit it by hand.
#import "BONSpecial.h"

@implementation BONSpecial

+ (NSString *)noBreakSpace { return @"\u00A0"; }
+ (NSString *)enSpace { return @"\u2002"; }
+ (NSString *)emSpace { return @"\u2003"; }
+ (NSString *)figureSpace { return @"\u2007"; }
+ (NSString *)thinSpace { return @"\u2009"; }
+ (NSString *)hairSpace { return @"\u200A"; }
+ (NSString *)zeroWidthSpace { return @"\u200B"; }
+ (NSString *)nonBreakingHyphen { return @"\u2011"; }
+ (NSString *)figureDash { return @"\u2012"; }
+ (NSString *)enDash { return @"\u2013"; }
+ (NSString *)emDash { return @"\u2014"; }
+ (NSString *)lineSeparator { return @"\u2028"; }
+ (NSString *)paragraphSeparator { return @"\u2029"; }
+ (NSString *)narrowNoBreakSpace { return @"\u202F"; }
+ (NSString *)wordJoiner { return @"\u2060"; }
+ (NSString *)minusSign { return @"\u2212"; }
+ (NSString *)objectReplacementCharacter { return @"\uFFFC"; }

@end
