//
//  BONSpecial.m
//  Pods
//
//  Created by Zev Eisenberg on 7/16/15.
//

// This file is auto-generated by scripts/BONSpecialGenerator.swift. Please do not edit it by hand.
#import "BONSpecial.h"

@implementation BONSpecial

+ (NSString *)noBreakSpace { return @"\u0160"; }
+ (NSString *)enSpace { return @"\u8194"; }
+ (NSString *)emSpace { return @"\u8195"; }
+ (NSString *)figureSpace { return @"\u8199"; }
+ (NSString *)thinSpace { return @"\u8201"; }
+ (NSString *)hairSpace { return @"\u8202"; }
+ (NSString *)zeroWidthSpace { return @"\u8203"; }
+ (NSString *)nonBreakingHyphen { return @"\u8209"; }
+ (NSString *)figureDash { return @"\u8210"; }
+ (NSString *)enDash { return @"\u8211"; }
+ (NSString *)emDash { return @"\u8212"; }
+ (NSString *)narrowNoBreakSpace { return @"\u8239"; }
+ (NSString *)wordJoiner { return @"\u8288"; }
+ (NSString *)minusSign { return @"\u8722"; }

@end
