//
//  BONSpecial.h
//  Pods
//
//  Created by Zev Eisenberg on 7/16/15.
//

// This file is auto-generated by scripts/BONSpecialGenerator.swift. Please do not edit it by hand.
@import Foundation;

@interface BONSpecial : NSObject

+ (NSString *)noBreakSpace;
+ (NSString *)enSpace;
+ (NSString *)emSpace;
+ (NSString *)figureSpace;
+ (NSString *)thinSpace;
+ (NSString *)hairSpace;
+ (NSString *)zeroWidthSpace;
+ (NSString *)nonBreakingHyphen;
+ (NSString *)figureDash;
+ (NSString *)enDash;
+ (NSString *)emDash;
+ (NSString *)lineSeparator;
+ (NSString *)paragraphSeparator;
+ (NSString *)narrowNoBreakSpace;
+ (NSString *)wordJoiner;
+ (NSString *)minusSign;
+ (NSString *)objectReplacementCharacter;

@end
