# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)
fastlane_require 'circleci_artifact'
fastlane_version "2.93.1"

BUILD_PATH="./build"
DERIVED_DATA_PATH = "#{BUILD_PATH}/derived_data"
PROJECT_NAME='BonMot.xcodeproj'

desc "Tests: iOS, tvOS, macOS. Builds: watchOS."
lane :coverage_all do
  bundle_ios = coverage(scheme: "BonMot-iOS", devices: get_devices(ios_latest: true, ios_10_3: true))
  bundle_tvos = coverage(scheme: "BonMot-tvOS")
  # For some reason fastlane tries to build for tvOS simulator unless destination is manually set
  bundle_macos = coverage(scheme: "BonMot-OSX", destination: "platform=macOS")
  
  xchtmlreport(result_bundle_paths: [bundle_ios, bundle_tvos, bundle_macos],
               enable_junit: true)
  # Unit testing is not available on watchOS
  xcodebuild(scheme: "BonMot-watchOS",
             derivedDataPath: DERIVED_DATA_PATH)
end

platform :mac do
  desc "Runs Tests & Generates Code Coverage Reports for macOS"
  lane :coverage_macos do
    coverage(scheme: "BonMot-OSX")
  end
end

platform :ios do
  desc "Runs Tests & Generates Code Coverage Reports for iOS 10.3.1 and latest iOS"
  lane :coverage_ios do
    devices = get_devices(ios_latest: true, ios_10_3: true)
    coverage(scheme: "BonMot-iOS",
             devices: devices)
  end

  desc "Runs Tests & Generates Code Coverage Reports for iOS 10.3.1"
  lane :coverage_ios_10_3 do
    devices = get_devices(ios_10_3: true)
    coverage(scheme: "BonMot-iOS",
             devices: devices)
  end

  desc "Runs Tests & Generates Code Coverage Reports for latest iOS"
  lane :coverage_ios_latest do
    devices = get_devices(ios_latest: true)
    coverage(scheme: "BonMot-iOS",
             devices: devices)
  end

  desc "Runs Tests & Generates Code Coverage Reports for tvOS"
  lane :coverage_tvos do
    coverage(scheme: "BonMot-tvOS")
  end

  # Tests cannot be run on watchOS
  desc "Build for watchOS"
  lane :build_watchos do
    xcodebuild(scheme: "BonMot-watchOS",
               derivedDataPath: DERIVED_DATA_PATH)
  end
end


def coverage(scheme:, devices: nil, destination: nil)
  scan_output_path = "#{BUILD_PATH}/#{scheme}/scan"

  # NOTE: Running too many devices concurrently breaks CircleCI resource limits
  disable_concurrent_testing = false
  if ENV['CIRCLE_BUILD_NUM']
    disable_concurrent_testing = true
  end

  begin
    scan(
      output_types: 'junit,html',
      devices: devices,
      destination: destination,
      scheme: scheme,
      output_directory: scan_output_path,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      result_bundle: true,
      disable_concurrent_testing: disable_concurrent_testing
    )
  rescue => ex
    # Don't fail the entire lane when running tests, but print failure to STDERR
    STDERR.puts ex
  end

  result_bundle_path = Scan.cache[:result_bundle_path]
  xccoverage_files = Dir.glob("#{Dir.pwd}/../#{result_bundle_path}/**/action.xccovreport").sort_by { |filename| File.mtime(filename) }.reverse
  xccov_file_direct_path = xccoverage_files.first

  slather_use_circleci = "false"

  if ENV['CIRCLE_BUILD_NUM']
    slather_use_circleci = "true"
  end

  xcov(
    project: PROJECT_NAME,
    scheme: scheme,
    output_directory: "#{BUILD_PATH}/#{scheme}/xcov",
    xccov_file_direct_path: xccov_file_direct_path
  )

  # Add binaries here as you create internal frameworks
  slather_binaries = ['BonMot']
  slather_output_directory = "#{BUILD_PATH}/#{scheme}/slather"

  # html and cobertura_xml output must be run separately
  slather(
    proj: PROJECT_NAME,
    scheme: scheme,
    binary_basename: slather_binaries,
    output_directory: slather_output_directory,
    html: "true",
    build_directory: DERIVED_DATA_PATH
  )
  # Using Cobertura XML allows us to upload to Codecov.io
  # Uploading to codecov is handled separately in the .circleci/config.yml
  slather(
    proj: PROJECT_NAME,
    scheme: scheme,
    binary_basename: slather_binaries,
    output_directory: slather_output_directory,
    circleci: slather_use_circleci,
    cobertura_xml: "true",
    build_directory: DERIVED_DATA_PATH
  )

  xchtmlreport(result_bundle_path: result_bundle_path,
               enable_junit: true)

  result_bundle_path
end

def get_devices(ios_latest: false, ios_10_3: false)
  # The full list of iOS simulators available on CircleCI
  # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
  devices = []
  if ios_latest
    devices.push("iPhone SE")
    devices.push("iPhone X")
    devices.push("iPhone 8")
    devices.push("iPhone 8 Plus")
    devices.push("iPad Pro (10.5-inch)")
  end

  if ios_10_3
    devices.push("iPhone SE (10.3.1)")
    devices.push("iPhone 7 (10.3.1)")
    devices.push("iPhone 7 Plus (10.3.1)")
    devices.push("iPad Pro (10.5-inch) (10.3.1)")
  end
  devices
end
